<script src="<?php echo e(asset('front/js/vendor/jquery-3.5.1.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/vendor/modernizr-3.5.0.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/vendor/waypoints.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/bootstrap.bundle.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/metismenu.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/slick.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/jquery.fancybox.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/isotope.pkgd.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/owl.carousel.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/jquery-ui-slider-range.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/ajax-form.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/wow.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/imagesloaded.pkgd.min.js')); ?>"></script>
<script src="<?php echo e(asset('front/js/main.js')); ?>"></script>
<?php /**PATH /home/pigstuhq/pureoproducts.pigslhub.com/resources/views/front/includes/partials/scripts.blade.php ENDPATH**/ ?>