<link rel="stylesheet" href="{{asset('front/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('front/css/preloader.css')}}">
<link rel="stylesheet" href="{{asset('front/css/slick.css')}}">
<link rel="stylesheet" href="{{asset('front/css/metismenu.css')}}">
<link rel="stylesheet" href="{{asset('front/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('front/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('front/css/jquery.fancybox.min.css')}}">
<link rel="stylesheet" href="{{asset('front/css/fontawesome5pro.css')}}">
<link rel="stylesheet" href="{{asset('front/css/ionicons.min.css')}}">
<link rel="stylesheet" href="{{asset('front/css/default.css')}}">
<link rel="stylesheet" href="{{asset('front/css/style.css')}}">